package com.jbk.hibernate;
// Generated Apr 29, 2020 10:33:47 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Download generated by hbm2java
 */
@Entity
@Table(name = "download", catalog = "hb")
public class Download implements java.io.Serializable {

	private int sr;
	private String version;
	private String name;
	private String vendor;
	private String bit32;
	private String bit64;
	private String common;
	private String officialSource;

	public Download() {
	}


	public Download(int sr, String name, String vendor, String bit32, String bit64, String common,
			String officialSource) {
		this.sr = sr;
		this.name = name;
		this.vendor = vendor;
		this.bit32 = bit32;
		this.bit64 = bit64;
		this.common = common;
		this.officialSource = officialSource;
	}

	@Id
	@Column(name = "sr", unique = true, nullable = false)
	public int getSr() {
		return this.sr;
	}

	public void setSr(int sr) {
		this.sr = sr;
	}

	@Column(name = "version", length = 45)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "vendor", length = 45)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "bit32", length = 45)
	public String getBit32() {
		return this.bit32;
	}

	public void setBit32(String bit32) {
		this.bit32 = bit32;
	}

	@Column(name = "bit64", length = 45)
	public String getBit64() {
		return this.bit64;
	}

	public void setBit64(String bit64) {
		this.bit64 = bit64;
	}

	@Column(name = "common", length = 45)
	public String getCommon() {
		return this.common;
	}

	public void setCommon(String common) {
		this.common = common;
	}

	@Column(name = "official_source", length = 45)
	public String getOfficialSource() {
		return this.officialSource;
	}

	public void setOfficialSource(String officialSource) {
		this.officialSource = officialSource;
	}

}
