package com.jbk.hibernate;
// Generated Apr 27, 2020 3:59:22 PM by Hibernate Tools 5.2.12.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;

/**
 * Statetable generated by hbm2java
 */
@Entity
@Table(name = "statetable", catalog = "hb")
public class Statetable implements java.io.Serializable {

	private int lid;
	private String state;

	public Statetable() {
	}

	public Statetable(int lid) {
		this.lid = lid;
	}

	public Statetable(int lid, String state) {
		this.lid = lid;
		this.state = state;
	}

	@Id

	@Column(name = "lid", unique = true, nullable = false)
	public int getLid() {
		return this.lid;
	}

	public void setLid(int lid) {
		this.lid = lid;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
